import { rm } from "node:fs/promises";

// These files are generated by export-static.mjs. Leaving the previous copies
// in public/ makes the next renderer see them as public assets and can freeze
// download links and patch-note fallbacks at the preceding release.
for (const path of [
  new URL("../public/index.html", import.meta.url),
  new URL("../public/market/index.html", import.meta.url),
]) {
  await rm(path, { force: true });
}
